config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#new'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :sessions

  resources :users
  resources :trips do
    resources :pictures
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :trip
  has_many :tags

  validates :photo, :attachment_presence => true
  has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  validates :user_id, presence: true
  validates :name, presence: true
  belongs_to :user
  has_many :pictures
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, presence: true
  validates :email, presence: true
  validates_uniqueness_of :username
  validates_uniqueness_of :email

  has_secure_password
  has_many :trips
  has_many :pictures
  has_many :tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @pictures = Picture.all
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @picture = Picture.new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @picture = Picture.create(picture_params)
    if @picture.valid?
      flash[:notice] = "Your picture has been added!"
      redirect_to trip_path(@trip)
    else
      flash[:alert] = "Something went wrong. Please try again."
      render "new"
    end
  end

  def edit
    @trip = Trip.find(params[:trip_id])
    @picture = Picture.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:trip_id])
    @picture = Picture.find(params[:id])
    if @picture.update(picture_params)
      flash[:notice] = "Your picture has been replaced."
      redirect_to trip_path(@trip)
    else
      flash[:alert] = "Something went wrong. Please try again."
      render "edit"
    end
  end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    flash[:alert] = "Your picture has been removed."
    redirect_to trip_path(@trip)
  end

private
  def picture_params
    params.require(:picture).permit(:photo).merge(:user_id => current_user.id, :trip_id => @trip.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
      flash[:notice] = "Logged in!"
    else
      flash[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_filter :authorize

  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.create(trip_params)
    if @trip.valid?
      flash[:notice] = "Your trip has been documented!"
      redirect_to trip_path(@trip)
    else
      flash[:alert] = "Something went wrong. Please try again."
      render "new"
    end
  end

  def show
    @trip = Trip.find(params[:id])
  end

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      flash[:notice] = "Your trip has been edited."
      redirect_to trip_path(@trip)
    else
      flash[:alert] = "Something went wrong. Please try again."
      render "edit"
    end
  end

  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    flash[:notice] = "Your trip has been removed."
    redirect_to user_path
  end

private
  def trip_params
    params.require(:trip).permit(:name).merge(:user_id => current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thanks for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripix</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class='container-fluid'>

<div id="nav-bar">
  <% if current_user %>
    Logged in as <%= link_to "#{current_user.username}", user_path(current_user) %>.
    <%= link_to "Log Out", logout_path %>
  <% else %>
    <%= link_to "Sign Up", signup_path %> or
    <%= link_to "Log In", login_path %>
  <% end %>
</div>

<%= image_tag("tripix-header.jpg", :alt => "image of Tripix header", :class => "header") %>

<%= yield %>

<%= flash[:notice] %>
<%= flash[:alert] %>


</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for [@trip, @picture], :html => { :multipart => true } do |f| %>
  <%= render('layouts/errors', :object => @picture) %>
  <%= f.file_field :photo %>
  <%= f.submit(:class => "btn btn-default") %>
<% end %>

app/views/pictures/edit.html.erb
<h2>Edit Your Picture</h2>

<p>Current Picture:</p>
<%= image_tag @picture.photo.url(:medium) %>

<%= render 'form' %>

app/views/pictures/new.html.erb
<h2>Add a Picture to <%= @trip.name %> Trip</h2>

<%= render 'form' %>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>

  <%= render('layouts/errors', :object => @trip) %>
  <div class="form-group">
    <%= f.label "Name:" %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "btn btn-default") %>
<% end %>

app/views/trips/edit.html.erb
<h2>Edit Your Trip</h2>

<%= render('form') %>

app/views/trips/new.html.erb
<h2>Add Your Trip</h2>

<%= render('form') %>

app/views/trips/show.html.erb
<h2><%= @trip.name %></h2>

<ul class="show_pix">
  <% @trip.pictures.each do |picture| %>
    <li class="pic"><%= image_tag picture.photo.url(:medium) %>
                    <%= link_to "replace", edit_trip_picture_path(@trip, picture), :class => "btn btn-success btn-xs" %>
                    <%= link_to "remove", trip_picture_path(@trip, picture), :class => "btn btn-primary btn-xs",
                      :data => {:confirm => "Are you sure you'd like to remove this trip?",
                                :method => "delete"} %>
    <li>
  <% end %>
</ul>

<%= link_to "Add Picture", new_trip_picture_path(@trip), :class => "btn btn-default" %><br>
<%= link_to "Home", root_path, :class => "btn btn-default" %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "layouts/errors", :object => @user %>
  <div class="form-group">
    <%= f.label "Username:" %>
    <%= f.text_field :username %>
  </div>
  <div class="form-group">
    <%= f.label "Email:" %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label "Password:" %>
    <%= f.text_field :password %>
  </div>
  <div class="form-group">
    <%= f.label "Password Confirmation:" %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up", :class => "btn btn-default" %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render 'form' %>
<br>

<%= link_to "Add Trip", new_trip_path, :class => 'btn btn-default' %>

app/views/users/show.html.erb
<h2>Profile for <%= @user.username %></h2>

<h3>Your Trips:</h3>
  <ul>
    <% @user.trips.each do |trip| %>
      <li><%= link_to "#{trip.name}", trip_path(trip) %> |
          <%= link_to "edit", edit_trip_path(trip) %> |
          <%= link_to "remove", trip_path(trip),
                      :data => {:confirm => "Are you sure you'd like to remove this trip?",
                                :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<%= link_to "Add Trip", new_trip_path, :class => "btn btn-default" %>
<%= link_to "Home", root_path, :class => "btn btn-default" %>